sonar.organization=hugopracticasprojectx
sonar.projectKey=hugopracticas_project-x
sonar.projectName=project-x
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.sourceEncoding=UTF-8

# Tests y cobertura (Jest)
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/*.test.js,**/*.test.jsx,src/setupTests.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
